INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 42, in mySQLscratch
    cursor.execute('CREATE TABLE Nike(NAME CHAR(100), SEX CHAR(1), PRICE CHAR(10))')
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1050, "Table 'Nike' already exists")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 40, in mySQLscratch
    conn = mysql.connect()
  File "/usr/local/lib/python3.6/dist-packages/flaskext/mysql.py", line 59, in connect
    return pymysql.connect(**self.connect_args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 40, in mySQLscratch
    conn = mysql.connect()
  File "/usr/local/lib/python3.6/dist-packages/flaskext/mysql.py", line 59, in connect
    return pymysql.connect(**self.connect_args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 40, in mySQLscratch
    conn = mysql.connect()
  File "/usr/local/lib/python3.6/dist-packages/flaskext/mysql.py", line 59, in connect
    return pymysql.connect(**self.connect_args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 40, in mySQLscratch
    conn = mysql.connect()
  File "/usr/local/lib/python3.6/dist-packages/flaskext/mysql.py", line 59, in connect
    return pymysql.connect(**self.connect_args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 40, in mySQLscratch
    conn = mysql.connect()
  File "/usr/local/lib/python3.6/dist-packages/flaskext/mysql.py", line 59, in connect
    return pymysql.connect(**self.connect_args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 40, in mySQLscratch
    conn = mysql.connect()
  File "/usr/local/lib/python3.6/dist-packages/flaskext/mysql.py", line 59, in connect
    return pymysql.connect(**self.connect_args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 68, in index
    mySQLscratch()
  File "/var/www/Frugally/Frugally/__init__.py", line 42, in mySQLscratch
    cursor.execute('CREATE TABLE IF NOT EXISTS Nike(NAME CHAR(100), SEX CHAR(1), PRICE CHAR(10))')
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1050, "Table 'Nike' already exists")
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
ERROR:Frugally:Exception on /sitemap.xml [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 108, in sitemap
    deltadays = datetime.now().ToString("yyy-MM-ddTHH:mm:sszzz") - timedelta(days=7)
AttributeError: 'datetime.datetime' object has no attribute 'ToString'
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
ERROR:Frugally:Exception on /sitemap.xml [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 108, in sitemap
    deltadays = datetime.now().ToString("yyy-MM-ddTHH:mm:sszzz") - timedelta(days=7)
AttributeError: 'datetime.datetime' object has no attribute 'ToString'
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s)' % item['vendor'], item['gender'], item['title'], item['brand'], item['retail-price'], item['price'], disc, item['image-link'], item['link'])
TypeError: not enough arguments for format string
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s)' % (item['vendor'], item['gender'], item['title'], item['brand'], item['retail-price'], item['price'], disc, item['image-link'], item['link']))
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Long Sleeve T-Shirt & Lounge Joggers Pajama 2-Piece Set, Lacoste, $68.00, $17.97' at line 1")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s)' % (item['vendor'], item['gender'], item['title'], item['brand'], item['retail-price'], item['price'], disc, item['image-link'], item['link']))
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Long Sleeve T-Shirt & Lounge Joggers Pajama 2-Piece Set, Lacoste, $68.00, $17.97' at line 1")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s);' % (item['vendor'], item['gender'], item['title'], item['brand'], item['retail-price'], item['price'], disc, item['image-link'], item['link']))
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Long Sleeve T-Shirt & Lounge Joggers Pajama 2-Piece Set, Lacoste, $68.00, $17.97' at line 1")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s);' % (item['vendor'], item['gender'], item['title'], item['brand'], item['retail-price'], item['price'], disc, item['image-link'], item['link']))
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Long Sleeve T-Shirt & Lounge Joggers Pajama 2-Piece Set, Lacoste, $68.00, $17.97' at line 1")
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?);' % (item['vendor'], item['gender'], item['title'], item['brand'], item['retail-price'], item['price'], disc, item['image-link'], item['link']))
TypeError: not all arguments converted during string formatting
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?);' % (str(item['vendor']), str(item['gender']), str(item['title']), str(item['brand']), str(item['retail-price']), str(item['price']), str(disc), str(item['image-link']), str(item['link'])))
TypeError: not all arguments converted during string formatting
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 494, in populateTables
    cursor.execute('INSERT INTO NordstromRackMen(vendor, gender, title, brand, retailprice, price, discount, imagelink, link) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?);', (str(item['vendor']), str(item['gender']), str(item['title']), str(item['brand']), str(item['retail-price']), str(item['price']), str(disc), str(item['image-link']), str(item['link'])))
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not all arguments converted during string formatting
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 69, in index
    populateTables()
  File "/var/www/Frugally/Frugally/__init__.py", line 497, in populateTables
    cursor.execute(sql, val)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/usr/local/lib/python3.6/dist-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not enough arguments for format string
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
INFO:Frugally:Nordstrom objects loaded: 40505
INFO:Frugally:Nike objects loaded: 192
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 507, in getNordstromContent
    with open('/var/www/Frugally/Frugally/nordstromracksales/NordstromRackMen.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/Frugally/Frugally/nordstromracksales/NordstromRackMen.json'
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 508, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5795 column 1 (char 2247388)
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 508, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8034 column 1 (char 3116316)
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 508, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8034 column 1 (char 3116316)
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 508, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8622 column 1 (char 3345428)
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 508, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8712 column 1 (char 3380298)
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 508, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 8812 column 1 (char 3420148)
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 530, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1596 column 1 (char 610792)
ERROR:Frugally:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/Frugally/Frugally/__init__.py", line 70, in index
    nordstrom = getNordstromContent()
  File "/var/www/Frugally/Frugally/__init__.py", line 530, in getNordstromContent
    data = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2957 column 1 (char 1144293)
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'women'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:women all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:[['sort', 'discount'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:[['gender', 'men'], ['vendors', 'all'], ['brands', 'all']]
INFO:Frugally:men all all
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
INFO:Frugally:Nordstrom objects loaded: 12499
INFO:Frugally:Nike objects loaded: 2640
